openapi: 3.0.2
x-stoplight:
  id: shbm2tdeqttj1
info:
  title: shriken_openapi
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /clubs:
    get:
      summary: get club list
      tags:
        - club
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  clubs:
                    type: array
                    items:
                      $ref: '#/components/schemas/Club'
              examples:
                my-example:
                  value:
                    clubs:
                      - clubColor: red
                        icon: /upload/club/1296/1325eed031d6c6a627abd1ff3ec5c295_180_180.jpeg
                        id: 1296
                        name: Seira FC Living room
                        plans:
                          - id: 1481
                            image: 'https://fanclove.s3.ap-northeast-1.amazonaws.com/club/plan-image/1296/UZK6XDFI.jpeg'
                            info: FC限定の内容を一緒に楽しみましょう♪
                            name: スタンダードプラン
                        slug: seira-livingroom
                      - clubColor: red
                        icon: /img/sample/logo/default.png
                        id: 1
                        name: FANCLOVEのファンクラブ
                        plans:
                          - id: 1784
                            image: null
                            info: 鍵アカサロンを試しに使ってみるためのプランです。入会メリットなどは特にありません。
                            name: 鍵アカサロン仮利用のためのプラン
                        slug: fanclove
                      - clubColor: aqua
                        icon: 'https://fanclove.s3.ap-northeast-1.amazonaws.com/club/icon/RNBTTOOFI25GTVWJ61KWTMCVTW3CSY.jpeg'
                        id: 4077
                        name: 心音ふぁんくラブ
                        plans:
                          - id: 5261
                            image: 'https://fanclove.s3.ap-northeast-1.amazonaws.com/club/plan-image/4077/N44FI231.jpeg'
                            info: "SNSでは見られない、写真、動画などの投稿が毎日見られる。佐々木心音をより身近に感じられて、応援できるプラン。\r\n\r\n\r\n「最近、SNS疲れをしていませんか？ほっこりするものだけ観たい、と思ったりする時が、癒される方が居てくださるのなら嬉しいな。　by 心音」"
                            name: 心音☺︎ぷらん
                        slug: kokone
                      - clubColor: red
                        icon: /upload/club/2826/5dc2b130aef8622cc122b64243134963_180_180.jpeg
                        id: 2826
                        name: マジシャンけんとのfanclub
                        plans:
                          - id: 3594
                            image: null
                            info: "レパートリー400を超えラスベガスで修行した私が無料で解説出来ないマジックを解説致します✨\r\n更にこの動画だけでは解らない！となっても大丈夫です。月に１回、時間をとりマンツーマンでレクチャー致します！"
                            name: マジシャンけんとのfanclub
                          - id: 3619
                            image: null
                            info: "レパートリー400を超えラスベガスで修行した私が無料で解説出来ないマジックを解説致します✨\r\n更にこの動画だけでは解らない！となっても大丈夫です。今後無制限マジックレクチャーをマンツーマンで行います！"
                            name: AD PREMIUM
                        slug: magic-kento
      operationId: get-clubs
      description: 入会しているクラブ一覧を取得する
      parameters: []
  '/clubs/{id}/channels':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
    get:
      summary: get club's channels
      tags:
        - club
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  channels:
                    type: array
                    items:
                      $ref: '#/components/schemas/Channel'
              examples:
                my-example:
                  value:
                    channels:
                      - IsOwner: true
                        createdAt: '2022-06-07T14:59:43+09:00'
                        description: test用のチャンネルです
                        id: 51
                        isJoinAsUser: true
                        name: test
                        plans:
                          - id: 1481
                            image: 'https://fanclove.s3.ap-northeast-1.amazonaws.com/club/plan-image/1296/UZK6XDFI.jpeg'
                            info: FC限定の内容を一緒に楽しみましょう♪
                            name: スタンダードプラン
                        updatedAt: '2022-06-07T14:59:43+09:00'
                      - IsOwner: true
                        createdAt: '2022-06-07T14:59:57+09:00'
                        description: test2用のチャンネルです
                        id: 52
                        isJoinAsUser: true
                        name: test2
                        plans:
                          - id: 1481
                            image: 'https://fanclove.s3.ap-northeast-1.amazonaws.com/club/plan-image/1296/UZK6XDFI.jpeg'
                            info: FC限定の内容を一緒に楽しみましょう♪
                            name: スタンダードプラン
                        updatedAt: '2022-06-07T14:59:57+09:00'
      operationId: get-clubs-id
      description: クラブに紐付いているチャネル一覧を取得する
  /channels:
    post:
      summary: create channel
      operationId: post-channels
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  channel:
                    $ref: '#/components/schemas/Channel'
              examples:
                my-example:
                  value:
                    channel:
                      id: 105
                      name: test!
                      description: test用のチャンネルです
                      isOwner: false
                      isJoinAsUser: true
                      plans:
                        - id: 1481
                          image: 'https://fanclove.s3.ap-northeast-1.amazonaws.com/club/plan-image/1296/UZK6XDFI.jpeg'
                          info: FC限定の内容を一緒に楽しみましょう♪
                          name: スタンダードプラン
                      createdAt: '2022-06-07T14:59:43+09:00'
                      updatedAt: '2022-06-07T14:59:43+09:00'
      description: チャネルの作成
      tags:
        - channel
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                description:
                  type: string
                plans:
                  type: array
                  items:
                    $ref: ./openapi.yaml#/components/schemas/Plan
              required:
                - name
                - description
                - plans
        description: ''
  '/channels/{id}':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
    delete:
      summary: delete channel
      operationId: delete-channels-id
      responses:
        '200':
          description: OK
      tags:
        - channel
  '/channels/{id}/channel_comments':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
    get:
      summary: get channel comments
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  channelComments:
                    type: array
                    items:
                      $ref: '#/components/schemas/ChannelComment'
                  nextCursor:
                    type: string
                    nullable: true
              examples:
                my-example:
                  value:
                    channelComments:
                      - id: 1
                        content: test!!!
                        profile:
                          id: 1
                          name: test_user
                          thumbnail: 'https://picsum.photos/id/237/200/300'
                          isProfilePublic: true
                        isRead: true
                        isDeleted: false
                        deletedAt: '2019-08-24T14:15:22Z'
                        createdAt: '2019-08-24T14:15:22Z'
                        updatedAt: '2019-08-24T14:15:22Z'
                        reactions:
                          - image: string
                            counts: 0
                            profiles:
                              - id: 0
                                name: string
                                thumbnail: string
                                isProfilePublic: true
                        threadInfo:
                          profiles:
                            - id: 2
                              name: test_user2
                              thumbnail: 'https://picsum.photos/seed/picsum/200/300'
                              isProfilePublic: true
                            - id: 3
                              name: test_user3
                              thumbnail: 'https://picsum.photos/id/1005/200/300'
                              isProfilePublic: true
                          commentCount: 2
                          lastCommentDateTime: '2019-08-24T14:15:22Z'
                      - id: 2
                        content: test投稿です！
                        profile:
                          id: 2
                          name: test_user2
                          thumbnail: 'https://picsum.photos/seed/picsum/200/300'
                          isProfilePublic: true
                        isRead: true
                        isDeleted: false
                        deletedAt: '2019-08-24T14:15:22Z'
                        createdAt: '2019-08-24T14:15:22Z'
                        updatedAt: '2019-08-24T14:15:22Z'
                        reactions:
                          - image: string
                            counts: 0
                            profiles:
                              - id: 0
                                name: string
                                thumbnail: string
                                isProfilePublic: true
                        threadInfo:
                          profiles:
                            - id: 1
                              name: test_user
                              thumbnail: 'https://picsum.photos/id/237/200/300'
                              isProfilePublic: true
                          commentCount: 0
                          lastCommentDateTime: '2019-08-24T14:15:22Z'
                    nextCursor: string
      operationId: get-channels-id-channel_comments
      tags:
        - channel_comment
      parameters:
        - schema:
            type: string
          in: query
          name: cursor
          description: ページネーション用
  /channel_comments:
    post:
      summary: create channel comment
      operationId: post-channel_comments
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  channelComment:
                    $ref: '#/components/schemas/ChannelComment'
      tags:
        - channel_comment
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                channelId:
                  type: integer
                threadStartCommentId:
                  type: integer
                  nullable: true
                profileId:
                  type: integer
                content:
                  type: string
                files:
                  type: array
                  items:
                    type: object
                    properties:
                      url:
                        type: string
                      contentType:
                        type: string
                        description: text/plain
        description: ''
      description: 投稿するテキスト、ファイルを登録する。
  '/channel_comments/{id}':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
    patch:
      summary: update channel comment
      operationId: patch-channel_comments-id
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  channelComment:
                    $ref: '#/components/schemas/ChannelComment'
      tags:
        - channel_comment
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                content:
                  type: string
        description: ''
    delete:
      summary: delete channel comment
      operationId: delete-channel_comments-id
      responses:
        '200':
          description: OK
      tags:
        - channel_comment
  /channel_comments/publish_pre_signed_url:
    post:
      summary: create pre-signed URL
      operationId: post-channel_comments-publish_pre_signed_url
      responses:
        '200':
          description: PreSignedUrlが、S3アップロード用のURLです。s3Urlが、コメント（ファイル）登録時のfilesのurlに埋め込むURLです。
          content:
            application/json:
              schema:
                type: object
                properties:
                  preSignedUrl:
                    type: string
                  s3Url:
                    type: string
      tags:
        - channel_comment
      description: ファイルアップロード用のPresignedURLを発行する
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                channelId:
                  type: integer
                fileName:
                  type: string
                contentType:
                  type: string
                  description: text/plain
        description: channelIdを送信してほしい理由は、ファイル保存場所のPath生成のためです。contentTypeは無くても良いといえば良いのですが、s3に登録する際のmetadataとして登録します。
components:
  schemas:
    Club:
      title: Club
      x-stoplight:
        id: shvootrff5ayu
      type: object
      x-internal: false
      x-examples: {}
      properties:
        id:
          type: integer
        slug:
          type: string
        name:
          type: string
        clubColor:
          type: string
        icon:
          type: string
          nullable: true
        plans:
          type: array
          items:
            $ref: '#/components/schemas/Plan'
    Plan:
      title: Plan
      x-stoplight:
        id: ja941ygq9tcik
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        info:
          type: string
          nullable: true
        image:
          type: string
          nullable: true
    Channel:
      title: Channel
      x-stoplight:
        id: hlury3t0lkij6
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        description:
          type: string
        isOwner:
          type: boolean
        isJoinAsUser:
          type: boolean
        plans:
          type: array
          items:
            $ref: '#/components/schemas/Plan'
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
    ChannelComment:
      title: ChannelComment
      x-stoplight:
        id: fwiwjsd39d1o9
      type: object
      properties:
        id:
          type: integer
        content:
          type: string
        profile:
          $ref: '#/components/schemas/Profile'
        isRead:
          type: boolean
        isDeleted:
          type: boolean
        deletedAt:
          type: string
          format: date-time
          nullable: true
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
        reactions:
          type: array
          items:
            $ref: '#/components/schemas/CommentReaction'
        threadInfo:
          type: object
          properties:
            profiles:
              type: array
              items:
                $ref: '#/components/schemas/Profile'
            commentCount:
              type: integer
            lastCommentDateTime:
              type: string
              format: date-time
    Profile:
      title: Profile
      x-stoplight:
        id: hwoemua95iq6t
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        thumbnail:
          type: string
          nullable: true
        isProfilePublic:
          type: boolean
    CommentReaction:
      title: CommentReaction
      x-stoplight:
        id: 1v12o75wh6474
      type: object
      properties:
        image:
          type: string
        counts:
          type: integer
        profiles:
          type: array
          items:
            $ref: '#/components/schemas/Profile'
