openapi: 3.0.2
info:
  title: shriken_openapi
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /clubs:
    get:
      summary: get club list
      tags:
        - club
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties: {}
      operationId: get-clubs
      description: 入会しているクラブ一覧を取得する
  '/clubs/{id}/channels':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
    get:
      summary: get club's channels
      tags:
        - club
      responses:
        '200':
          description: OK
      operationId: get-clubs-id
      description: クラブに紐付いているチャネル一覧を取得する
  /channels:
    post:
      summary: create channel
      operationId: post-channels
      responses:
        '200':
          description: OK
      description: チャネルの作成
      tags:
        - channel
  '/channels/{id}':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
    get:
      summary: get channel
      tags:
        - channel
      responses:
        '200':
          description: OK
      operationId: get-channels-id
      description: チャネルに紐付いているコメント一覧を取得する
    delete:
      summary: delete channel
      operationId: delete-channels-id
      responses:
        '200':
          description: OK
      tags:
        - channel
  /channel_comments:
    post:
      summary: create channel comment
      operationId: post-channel_comments
      responses:
        '200':
          description: OK
      tags:
        - channel_comment
  '/channel_comments/{id}':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
    patch:
      summary: update channel comment
      operationId: patch-channel_comments-id
      responses:
        '200':
          description: OK
      tags:
        - channel_comment
    delete:
      summary: delete channel comment
      operationId: delete-channel_comments-id
      responses:
        '200':
          description: OK
      tags:
        - channel_comment
  /channel_comments/publish_pre_signed_url:
    post:
      summary: create pre-signed URL
      operationId: post-channel_comments-publish_pre_signed_url
      responses:
        '200':
          description: OK
      tags:
        - channel_comment
      description: ファイルアップロード用のPresignedURLを発行する
components:
  schemas: {}
