openapi: 3.0.2
info:
  title: shriken_openapi
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /clubs:
    get:
      summary: get club list
      tags:
        - club
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  clubs:
                    type: array
                    items:
                      type: object
                      properties:
                        plans:
                          type: array
                          items:
                            type: object
                            properties:
                              id:
                                type: integer
                              name:
                                type: string
                              info:
                                type: string
                                nullable: true
                              image:
                                type: string
                                nullable: true
                        id:
                          type: integer
                        slug:
                          type: string
                        name:
                          type: string
                        clubColor:
                          type: string
                        icon:
                          type: string
                          nullable: true
              examples:
                example:
                  value:
                    clubs:
                      - plans:
                          - id: 0
                            name: string
                            info: string
                            image: string
                        id: 0
                        slug: string
                        name: string
                        clubColor: string
                        icon: string
                my-example:
                  value:
                    clubs:
                      - clubColor: red
                        icon: /upload/club/1296/1325eed031d6c6a627abd1ff3ec5c295_180_180.jpeg
                        id: 1296
                        name: Seira FC Living room
                        plans:
                          - id: 1481
                            image: 'https://fanclove.s3.ap-northeast-1.amazonaws.com/club/plan-image/1296/UZK6XDFI.jpeg'
                            info: FC限定の内容を一緒に楽しみましょう♪
                            name: スタンダードプラン
                        slug: seira-livingroom
                      - clubColor: red
                        icon: /img/sample/logo/default.png
                        id: 1
                        name: FANCLOVEのファンクラブ
                        plans:
                          - id: 1784
                            image: null
                            info: 鍵アカサロンを試しに使ってみるためのプランです。入会メリットなどは特にありません。
                            name: 鍵アカサロン仮利用のためのプラン
                        slug: fanclove
                      - clubColor: aqua
                        icon: 'https://fanclove.s3.ap-northeast-1.amazonaws.com/club/icon/RNBTTOOFI25GTVWJ61KWTMCVTW3CSY.jpeg'
                        id: 4077
                        name: 心音ふぁんくラブ
                        plans:
                          - id: 5261
                            image: 'https://fanclove.s3.ap-northeast-1.amazonaws.com/club/plan-image/4077/N44FI231.jpeg'
                            info: "SNSでは見られない、写真、動画などの投稿が毎日見られる。佐々木心音をより身近に感じられて、応援できるプラン。\r\n\r\n\r\n「最近、SNS疲れをしていませんか？ほっこりするものだけ観たい、と思ったりする時が、癒される方が居てくださるのなら嬉しいな。　by 心音」"
                            name: 心音☺︎ぷらん
                        slug: kokone
                      - clubColor: red
                        icon: /upload/club/2826/5dc2b130aef8622cc122b64243134963_180_180.jpeg
                        id: 2826
                        name: マジシャンけんとのfanclub
                        plans:
                          - id: 3594
                            image: null
                            info: "レパートリー400を超えラスベガスで修行した私が無料で解説出来ないマジックを解説致します✨\r\n更にこの動画だけでは解らない！となっても大丈夫です。月に１回、時間をとりマンツーマンでレクチャー致します！"
                            name: マジシャンけんとのfanclub
                          - id: 3619
                            image: null
                            info: "レパートリー400を超えラスベガスで修行した私が無料で解説出来ないマジックを解説致します✨\r\n更にこの動画だけでは解らない！となっても大丈夫です。今後無制限マジックレクチャーをマンツーマンで行います！"
                            name: AD PREMIUM
                        slug: magic-kento
      operationId: get-clubs
      description: 入会しているクラブ一覧を取得する
      parameters:
        - schema:
            type: string
          in: header
  '/clubs/{id}/channels':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
    get:
      summary: get club's channels
      tags:
        - club
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  channels:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        name:
                          type: string
                        description:
                          type: string
                        createdAt:
                          type: string
                          description: '2022-06-07T14:59:57+09:00'
                        updatedAt:
                          type: string
                          description: '2022-06-07T14:59:57+09:00'
      operationId: get-clubs-id
      description: クラブに紐付いているチャネル一覧を取得する
  /channels:
    post:
      summary: create channel
      operationId: post-channels
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  description:
                    type: string
                  planIds:
                    type: array
                    items:
                      type: integer
      description: チャネルの作成
      tags:
        - channel
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: チャンネル名
                description:
                  type: string
                  description: チャンネル説明
                planIds:
                  type: array
                  description: 紐付けるPlanID
                  items:
                    type: integer
  '/channels/{id}':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
    get:
      summary: get channel
      tags:
        - channel
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  description:
                    type: string
                  comments:
                    type:
                      - string
                      - array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        content:
                          type: string
                          description: コメントの内容
                        profile:
                          type: object
                          properties:
                            id:
                              type: integer
                            name:
                              type: string
                            thumbnail:
                              type: string
                              nullable: true
                            isProfilePublic:
                              type: boolean
                        threadInfo:
                          type: object
                          nullable: true
                          properties:
                            profiles:
                              type: array
                              items:
                                type: object
                                properties:
                                  id:
                                    type: integer
                                  name:
                                    type: string
                                  thumbnail:
                                    type: string
                                    nullable: true
                                  isProfilePublic:
                                    type: boolean
                            commentCount:
                              type: integer
                            lastCommentDateTime:
                              type: string
                              description: '2022-06-07T14:59:57+09:00'
                        reactions:
                          type: array
                          items:
                            type: object
                            properties:
                              profiles:
                                type: array
                                items:
                                  type: object
                                  properties:
                                    id:
                                      type: integer
                                    name:
                                      type: string
                              image:
                                type: string
                              counts:
                                type: integer
                        isRead:
                          type: boolean
                        isDeleted:
                          type: boolean
                        deletedAt:
                          type: string
                          nullable: true
                        createdAt:
                          type: string
                        updatedAt:
                          type: string
      operationId: get-channels-id
      description: チャネルに紐付いているコメント一覧を取得する
    delete:
      summary: delete channel
      operationId: delete-channels-id
      responses:
        '200':
          description: OK
      tags:
        - channel
  /channel_comments:
    post:
      summary: create channel comment
      operationId: post-channel_comments
      responses:
        '200':
          description: OK
      tags:
        - channel_comment
  '/channel_comments/{id}':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
    patch:
      summary: update channel comment
      operationId: patch-channel_comments-id
      responses:
        '200':
          description: OK
      tags:
        - channel_comment
    delete:
      summary: delete channel comment
      operationId: delete-channel_comments-id
      responses:
        '200':
          description: OK
      tags:
        - channel_comment
  /channel_comments/publish_pre_signed_url:
    post:
      summary: create pre-signed URL
      operationId: post-channel_comments-publish_pre_signed_url
      responses:
        '200':
          description: OK
      tags:
        - channel_comment
      description: ファイルアップロード用のPresignedURLを発行する
components:
  schemas: {}
